version: '3.8'

volumes:
  kanalservice_db:

services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - kanalservice_db:/var/lib/postgresql/data/
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  script:
    build:
      context: .
    command: python3 script.py
    restart: always
    env_file:
      - .env
    depends_on:
      - db
